# basic options
title: Sage Days 2022 
author: GitHub User
email: your-email@domain.com
description: Site under construction
github_username:  meesue

# Build settings
markdown: kramdown
theme: jekyll-theme-architect
